const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ055YnBGVjBEb2lyWUpkR29uYU4xTW9ZQjVTQzNOdDlxNlZ0Ti9zbnpGRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTEVuaTdaTklqbkZkQWMxNk5Wd0VkNGhxN0lGT09TdytXRm5vU2psZ3FTST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrQU5MQWNIU1FGTWN6cmdBeGplaFpoMlgxc0VSUEU3QXFld1I2UHRCeDJjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6N09nbHlMeFZaMmJQdGtGMDVEV3BNc1hQYVRsL3VUNStRRk9SckZCYlNFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktBeU9VSEZVQjM2dG9ueEU3WWJtajJjVHhjbnhmaS9aNEU2WjBVWTRWRjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZXMHZQUnNDYnJBYy9xNnF6SGZaRlB1OG41SDFNalczQkh0KzJhQzgzem89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUFKN21raHo4aVZoNzBuZmo1RlRwemZBQ2xYTzIxS0NFdlA4L01nbEJXYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibzRmZFR4Y3dza2QvRWllbzNyUWpOZWN6MU5YL3ErMzhDS2tuZzdhN29Iaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxWZXpSSGF6YkJzOC9WMHN5dy9iZ2xpN3ZCc2o2Y2FCRW12bzN6ZHRJVTlTUTJQWjV2Zi95bnpOV0lpY0ZzR0h5ZU11djdJQkc3d3llNEt5WWFFRGd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTczLCJhZHZTZWNyZXRLZXkiOiJuclBKbWx5MWExTzZ5aE13TEdHaTgvVVA0WllSdHB4VlRlaTU2TzNXcGp3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOnRydWV9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkJLQklLOVFXIiwibWUiOnsiaWQiOiIyNTQxMTI1ODE4MTA6OUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjE4ODA3NzI3MjI0ODUyMzo5QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTjJSNGNJREVPdmFsODBHR0FJZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQi82VmV3MXpzVDk1QVd2eDluVnA5VWd3TTdIbjhYV29oY2s4WTBZRjZpMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiWmVYMXBPUHJsYW5OQ0Zia2kyMWpseWRnVHJFK3h4WU5PY1R0S29LWU9Pc0d4Y2tCYS9tK0FlWWZuN3RJZWVHbkhDcXNmbStHbmlET0gvZG42VDMyREE9PSIsImRldmljZVNpZ25hdHVyZSI6IjRMblVBZXhWMDRvZnk5QTVudHNJUGJVNFlnZC9LbFREM2dSbzZjT3A0c1hNRzNRdS9jcksyazdwRTBHNFNnTWRGekJtZjBmWFY4QXJZdFRyN3l2YmlnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0MTEyNTgxODEwOjlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUWYrbFhzTmM3RS9lUUZyOGZaMWFmVklNRE94NS9GMXFJWEpQR05HQmVvdCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSURRZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzcyNDgxOTEwLCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTWdPIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
