const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUg2aUdBby9mM2ZNQmpCMEsrME16bm1nYTJRY0V4a2p3aDFrcHNEM1FsTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTDdXMy9weFpTUmJxQVNVNVJJU3FSRDJ6aVhMYXNRcEZ3MVNuTnZDRktsRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrTDJGOVdxQzNRNDdPSnJnWVJSa2NETjdzZFZtVTZiUVpDVHdIeHFOOW5jPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzOFI0WXRiS2JNM2oxdnM5QklEL0M4NzFXU0NUTXgzVVpSdEtDQi9pendrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNLWE5tYm5SeDNOekI1RDFSR1k5aHJPNm5WTzFxWXpJQkphRjBST0FKMzA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjkxbkpYNGtXNUNPcFh0eUZFaEU3cjdEcmRkOXBOWGY1elRoeWhPZUNzUzg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0lVZEEvdURKZ2g2VmM3UkF1U2ZnK1NiZllONU1mT1VjRFBhNy9mczdVRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTHZBOTVLREFXb01IYTNaQkNjOTdwNHdXQzQraWNPU0JvMXEydDNkRWEzbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdKZ2cxTkFOcEI5ZFZYd3Zhb3hFbXRQNnBTUHpERlVLcjBIeXpQdmhBdXY5SENNR0l0TVRJWldMRDIzSlUwV3A1TnpLU1R2UHo0Z0QxZmFUaGVwbWlnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQwLCJhZHZTZWNyZXRLZXkiOiJRNFMyMXkvTVBoYXYxamYvenFmaDFxdnB1WEsvR0JycVZRaDN4Q1BXRGpnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOnRydWV9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjAwWThHQTkwIiwibWUiOnsiaWQiOiIyNTQxMTI1ODE4MTA6MTBAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxODgwNzcyNzIyNDg1MjM6MTBAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOMlI0Y0lERVBmaGw4MEdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJCLzZWZXcxenNUOTVBV3Z4OW5WcDlVZ3dNN0huOFhXb2hjazhZMFlGNmkwPSIsImFjY291bnRTaWduYXR1cmUiOiJwNkFCU09nNnBVMWJiZFBQUlRTU0RPMTVGRHNsY0wyV2FmQll6WVBEV0pJT0FiVitjcjNpSlRuMndPRlJoN3Jnalgrb1dBbkNmdTRWREtHK2ZiaFpBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiSmZTQld5WDJ1dENudmZLVDhwaWVNUzZHbzRsMDFpaHJpTTBrMjJFUXErVFhBRGdMeHR6U0gvNkRRU0xQNzZJeVZkZmpKSFUwVktiS2hNR3VEU084aUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQxMTI1ODE4MTA6MTBAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUWYrbFhzTmM3RS9lUUZyOGZaMWFmVklNRE94NS9GMXFJWEpQR05HQmVvdCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSURRZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzcyNDgyODE2LCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTWdPIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
